### ISSUE TITLE
post installation failure

### ISSUE THREAD

**Issue by amimimor** [karreiro/dmn-cli#3]
Thanks for your work.
I've installed `dmn-cli` using `npm i -g dmn-cli`
And I'm getting the following exception:
```
/usr/local/lib/node_modules/dmn-cli/dist/fetchTypes/javaToDmnConverter.js:12
        children: dataType.children?.map((dt) => convertDataType(dt, customTypes)) || [],
                                    ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:1054:16)
    at Module._compile (internal/modules/cjs/loader.js:1102:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/dmn-cli/dist/fetch-types.js:9:30)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
```

My setup is:

MacOS 11.2.3 (Big Sur)
NPM 7.10.0
Node v12.18.1

**Comment by amimimor** [comment]
Update: solved by upgrading node to v16.0.0
